### ISSUE TITLE
Shapes appear distorted or with clipped previews in Gliffy

### ISSUE THREAD

**Issue by ianbrandt** [codeclou/enterprise-integration-pattern-shapes-for-gliffy#8]
When I add the shapes as a [custom shape library](https://help.gliffy.com/online/Content/GliffyCommon/Adding-custom-shape-libraries.htm) in Gliffy for Confluence 9.4.1 some appear squashed horizontally, or their previews in the [shape library sidebar](https://help.gliffy.com/online/Content/GliffyCommon/Shape-libraries.htm) are off-center and vertically clipped, or both.

The shapes all look fine when I open them directly with the Chrome or Edge browsers.

I notice Gliffy's custom shape library help specifies that "SVG files cannot contain inline stylesheets." Viewing the SVG source for some of the shapes I can see they do make use of inline [`style`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style) attributes. Pure speculation, but perhaps that is the cause of the incompatibility.

**Comment by clouless** [comment]
We are currently reworking all SVGs.
The branch is not merged yet, but you try them out already:
https://github.com/codeclou/enterprise-integration-pattern-shapes-for-gliffy/tree/feature/site-redesign/docimg/svg

It will take some time for us to publish the new branch since it still needs some work.

**Comment by ianbrandt** [comment]
The previews for the redesigned shapes still seem to appear distorted or off center and clipped in the sidebar; however, all the ones I've tried do look okay when added to a diagram. That makes them usable for my purposes. Thanks!

**Comment by clouless** [comment]
I have tried the new ones in Gliffy diagram and in the sidebar. It looks ok for me:

<img width="1446" alt="Bildschirmfoto 2021-12-16 um 09 06 38" src="https://user-images.githubusercontent.com/12599965/146332217-4dcfe927-a370-4f63-b76b-ce7a9e6089cc.png">

I am using Gliffy 9.1.2 and Confluence 7.3.1

**Comment by clouless** [comment]
Ok after upgrading to Gliffy 9.4.1 the sidebar is stretching the shapes.

![image](https://user-images.githubusercontent.com/12599965/146332678-88775253-201a-45d2-8e59-76bc2a77a0e4.png)

I think this seems to be a Gliffy problem, but we will see if we can do something about it on our end.

**Comment by ianbrandt** [comment]
Thanks. That's how they look in my Gliffy for Confluence instance as well.

**Comment by clouless** [comment]
Answer from Gliffy Support: `I wanted to follow-up on this to let you know that development has identified this as a new bug for that version. `

So I will close this issue, since Gliffy will fix it on their end. I do not know when and in which version, but I guess in the upcoming gliffy releases this will be fixed :)
